### ISSUE TITLE
Livereload causes crash on any change

### ISSUE THREAD

**Issue by austinmao** [Karnith/machinepack-sailsgulpify#5]
After follow install instructions and running `gulp` at the command line, any file change results in the following:

```
/Users/austinmao/Sites/sails-mongoose-boilerplate/tasks-gulp/config/watch.js:19
                    server.changed(file.path);
                           ^

TypeError: server.changed is not a function
  at EventEmitter.<anonymous> (/Users/austinmao/Sites/sails-mongoose-boilerplate/tasks-gulp/config/watch.js:19:13)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
  at Gaze.<anonymous> (/Users/austinmao/Sites/sails-mongoose-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:17:11)
  at emitTwo (events.js:87:13)
  at Gaze.emit (events.js:172:7)
  at Gaze.emit (/Users/austinmao/Sites/sails-mongoose-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
  at /Users/austinmao/Sites/sails-mongoose-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:415:16
  at StatWatcher._pollers.(anonymous function) (/Users/austinmao/Sites/sails-mongoose-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:326:7)
  at emitTwo (events.js:87:13)
  at StatWatcher.emit (events.js:172:7)
  at StatWatcher._handle.onchange (fs.js:1291:10)
```

**Comment by austinmao** [comment]
If this helps, here is my packages.json for gulp dependencies:

```
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-cache": "^0.3.0",
    "gulp-changed": "^1.3.0",
    "gulp-coffee": "^2.3.1",
    "gulp-concat": "^2.6.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-jade": "^1.1.0",
    "gulp-jshint": "^1.12.0",
    "gulp-less": "^3.0.3",
    "gulp-linker": "^0.1.7",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.0.0",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-rimraf": "^0.2.0",
    "gulp-sass": "^2.1.0",
    "gulp-template-compile": "^1.1.0",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.7",
```

**Comment by Karnith** [comment]
yeah, live reload decided to completely change their api....

Try this as a workaround until I update the module

watch.js

```
/**
 * Run predefined tasks whenever watched file patterns are added, changed or deleted.
 *
 * ---------------------------------------------------------------
 *
 * Watch for changes on
 * - files in the `assets` folder
 * - the `tasks/pipeline.js` file
 * and re-run the appropriate tasks.
 *
 *
 */
module.exports = function(gulp, plugins, growl) {
    //var server = plugins.livereload();
    gulp.task('watch:api', function() {
        // Watch Style files
    var server = plugins.livereload();
        return gulp.watch('api/**/*', ['syncAssets']);
                //.on('change', function(file) {
                //  server.changed(file.path);
                //});
    });

    gulp.task('watch:assets', function() {
        // Watch assets
    var server = plugins.livereload();
        return gulp.watch(['assets/**/*', 'tasks/pipeline.js'], ['syncAssets']);
                //.on('change', function(file) {
                //  server.changed(file.path);
                //});
    });

};
```

Let me know how you get on...

**Comment by austinmao** [comment]
I still got the same error with this change

**Comment by Karnith** [comment]
I'll look at it today and make the changes needed. I have it working on my system.

JCMAR
Matthew Marino
mmarino@jcmar.com
P: +1 (206) 612-1725

-------- Original message --------

**Comment by davidsoderberg** [comment]
I got exact same issue on my computer.

**Comment by Karnith** [comment]
what version of sails are you guys using? could you post your gulp dependencies and anything else that might help.

**Comment by davidsoderberg** [comment]
this is my dependencies:
    "bootstrap-sass": "^3.3.6",
    "ejs": "2.3.4",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-cache": "^0.4.2",
    "gulp-changed": "^1.3.0",
    "gulp-concat": "^2.6.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-jshint": "^2.0.0",
    "gulp-linker": "^0.1.7",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.2.0",
    "gulp-minify-css": "^1.2.3",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-rimraf": "^0.2.0",
    "gulp-sass": "^2.2.0",
    "gulp-template-compile": "^1.1.0",
    "gulp-uglify": "^1.5.2",
    "gulp-util": "^3.0.7",
    "include-all": "~0.1.6",
    "istanbul": "^0.4.2",
    "jshint": "^2.9.1",
    "machinepack-prompts": "^0.5.0",
    "machinepack-sailsgulpify": "^1.0.1",
    "mocha": "^2.4.5",
    "rc": "1.0.1",
    "rimraf": "^2.5.2",
    "run-sequence": "^1.1.5",
    "sails": "~0.12.1",
    "sails-disk": "~0.10.9",
    "sails-hook-autoreload": "^0.13.1",
    "sails-mysql": "^0.11.4"

**Comment by wfpaisa** [comment]
hello, I have the same problem, any solution?

**Comment by wfpaisa** [comment]
this my solution:

``` javascript
/**
 * Run predefined tasks whenever watched file patterns are added, changed or deleted.
 *
 * ---------------------------------------------------------------
 *
 * Watch for changes on
 * - files in the `assets` folder
 * - the `tasks/pipeline.js` file
 * and re-run the appropriate tasks.
 *
 *
 */
module.exports = function(gulp, plugins, growl) {
    var server = plugins.livereload;
    server.listen();

    gulp.task('watch:api', function() {
        // Watch Style files
        return gulp.watch('api/**/*', ['syncAssets'])
                .on('change', function(file) {
                    server.changed(file.path);
                });
    });

    gulp.task('watch:assets', function() {
        // Watch assets
        return gulp.watch(['assets/**/*', 'tasks/pipeline.js'], ['syncAssets'])
                .on('change', function(file) {
                    server.changed(file.path);
                });
    });

};
```

`var server = plugins.livereload();` -> `var server = plugins.livereload;`
add: server.listen();

**Comment by Karnith** [comment]
auto reload should e fixed now. will push to npm shortly.

**Comment by wfpaisa** [comment]
thank you
